import VoiceInterface from "@/components/VoiceInterface";
import MetricsSidebar from "@/components/MetricsSidebar";
import CareerTimeline from "@/components/CareerTimeline";

export default function Home() {
  return (
    <div className="min-h-screen bg-bg text-ink">
      {/* ── Top bar ── */}
      <header className="border-b border-border px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <span className="text-xs font-mono tracking-widest text-muted uppercase">
            Portfolio
          </span>
          <span className="text-muted-2">·</span>
          <span className="text-xs font-mono tracking-widest text-gold uppercase">
            AI-Assisted
          </span>
        </div>
        <a
          href="mailto:jtaitwalker@gmail.com"
          className="text-xs text-muted hover:text-ink transition-colors tracking-wide"
        >
          jtaitwalker@gmail.com
        </a>
      </header>

      {/* ── Hero ── */}
      <section className="px-6 pt-14 pb-10 border-b border-border">
        <div className="max-w-5xl mx-auto">
          <p className="text-xs tracking-[0.2em] text-muted uppercase mb-4 font-mono">
            London, UK · Open to opportunities
          </p>
          <h1 className="font-display text-5xl sm:text-6xl lg:text-7xl font-bold text-ink leading-none tracking-tight mb-4">
            Jamal Walker
          </h1>
          <p className="text-gold font-display text-xl sm:text-2xl italic mb-5">
            Senior Account Executive
          </p>
          <p className="text-muted max-w-xl text-sm leading-relaxed">
            Enterprise SaaS · AI, Data &amp; Fintech Platforms · 9+ years
            closing six-figure ARR deals across UK &amp; EMEA. Net-new pipeline
            builder. Quota-crusher. GTM architect.
          </p>
        </div>
      </section>

      {/* ── Main content ── */}
      <main className="max-w-5xl mx-auto px-6 py-12">
        {/* Mobile metrics — shown above fold on small screens */}
        <div className="block lg:hidden mb-10">
          <MetricsSidebar inline />
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-[1fr_260px] gap-10">
          {/* Left column */}
          <div className="space-y-12">
            <VoiceInterface />
            <CareerTimeline />
          </div>

          {/* Right sidebar — hidden on mobile (shown above instead) */}
          <div className="hidden lg:block">
            <MetricsSidebar />
          </div>
        </div>
      </main>

      {/* ── Footer ── */}
      <footer className="border-t border-border px-6 py-6 mt-8">
        <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <p className="text-xs text-muted">
            Answers generated by Claude, grounded in Jamal&apos;s CV only.
          </p>
          <div className="flex items-center gap-4 text-xs text-muted">
            <a
              href="https://linkedin.com/in/jamal-walker-cloud"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-gold transition-colors"
            >
              LinkedIn
            </a>
            <span className="text-muted-2">·</span>
            <span>07947 886539</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
