import Image from "next/image";
import VoiceInterface from "@/components/VoiceInterface";
import MetricsSidebar from "@/components/MetricsSidebar";
import CareerTimeline from "@/components/CareerTimeline";

export default function Home() {
  return (
    <div className="min-h-screen bg-bg text-ink">
      {/* ── Top bar ── */}
      <header className="border-b border-border px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <span className="text-xs font-mono tracking-widest text-muted uppercase">
            Portfolio
          </span>
          <span className="text-muted-2">·</span>
          <span className="text-xs font-mono tracking-widest text-gold uppercase">
            AI-Assisted
          </span>
        </div>
        <a
          href="mailto:jtaitwalker@gmail.com"
          className="text-xs text-muted hover:text-ink transition-colors tracking-wide"
        >
          jtaitwalker@gmail.com
        </a>
      </header>

      {/* ── Hero ── */}
      <section className="px-6 pt-14 pb-10 border-b border-border">
        <div className="max-w-5xl mx-auto">
          <div className="flex items-center gap-8 sm:gap-10">
            {/* Headshot */}
            <div className="flex-shrink-0">
              <div className="w-24 h-24 sm:w-32 sm:h-32 lg:w-36 lg:h-36 rounded-full overflow-hidden border-2 border-gold/40 ring-4 ring-gold/10 shadow-[0_0_40px_rgba(200,168,75,0.12)]">
                <Image
                  src="/jamal.jpg"
                  alt="Jamal Walker"
                  width={144}
                  height={144}
                  className="object-cover w-full h-full"
                  priority
                />
              </div>
            </div>

            {/* Text */}
            <div>
              <p className="text-xs tracking-[0.2em] text-muted uppercase mb-3 font-mono">
                London, UK · Open to opportunities
              </p>
              <h1 className="font-display text-5xl sm:text-6xl lg:text-7xl font-bold text-ink leading-none tracking-tight mb-3">
                Jamal Walker
              </h1>
              <p className="text-gold font-display text-xl sm:text-2xl italic mb-4">
                Senior Account Executive
              </p>
              <p className="text-muted max-w-xl text-sm leading-relaxed">
                Enterprise SaaS · AI, Data &amp; Fintech Platforms · 9+ years
                closing six-figure ARR deals across UK &amp; EMEA. Net-new
                pipeline builder. Quota-crusher. GTM architect.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ── Main content ── */}
      <main className="max-w-5xl mx-auto px-6 py-12 pb-28">
        {/* Mobile metrics — shown above fold on small screens */}
        <div className="block lg:hidden mb-10">
          <MetricsSidebar inline />
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-[1fr_260px] gap-10">
          {/* Left column */}
          <div className="space-y-12">
            <VoiceInterface />
            <CareerTimeline />
          </div>

          {/* Right sidebar — hidden on mobile (shown above instead) */}
          <div className="hidden lg:block">
            <MetricsSidebar />
          </div>
        </div>
      </main>

      {/* ── Footer ── */}
      <footer className="border-t border-border px-6 py-6 mt-8 mb-16">
        <div className="max-w-5xl mx-auto">
          <p className="text-xs text-muted">
            Answers generated by Claude, grounded in Jamal&apos;s CV only.
          </p>
        </div>
      </footer>

      {/* ── Sticky contact strip ── */}
      <div className="fixed bottom-0 left-0 right-0 z-50 bg-[#0a1628]/95 backdrop-blur-sm border-t border-gold/20">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 py-3 flex items-center justify-between gap-2 sm:gap-6">
          {/* Email */}
          <a
            href="mailto:jtaitwalker@gmail.com"
            className="flex items-center gap-1.5 text-xs text-muted hover:text-gold transition-colors min-w-0"
          >
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" className="flex-shrink-0">
              <rect x="2" y="4" width="20" height="16" rx="2"/>
              <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/>
            </svg>
            <span className="hidden sm:inline">jtaitwalker@gmail.com</span>
            <span className="sm:hidden">Email</span>
          </a>

          <span className="text-muted-2 hidden sm:inline">·</span>

          {/* LinkedIn */}
          <a
            href="https://linkedin.com/in/jamal-walker-cloud"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-1.5 text-xs text-muted hover:text-gold transition-colors"
          >
            <svg width="13" height="13" viewBox="0 0 24 24" fill="currentColor" className="flex-shrink-0">
              <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/>
              <rect x="2" y="9" width="4" height="12"/>
              <circle cx="4" cy="4" r="2"/>
            </svg>
            <span className="hidden sm:inline">linkedin.com/in/jamal-walker-cloud</span>
            <span className="sm:hidden">LinkedIn</span>
          </a>

          <span className="text-muted-2 hidden sm:inline">·</span>

          {/* Book a call */}
          <a
            href="https://calendar.app.google/c5HUsWTMEd3GJtMr8"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-1.5 px-3 py-1.5 rounded border border-gold/40 text-xs text-gold hover:bg-gold/10 transition-all font-mono tracking-wide flex-shrink-0"
          >
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" className="flex-shrink-0">
              <rect x="3" y="4" width="18" height="18" rx="2" ry="2"/>
              <line x1="16" y1="2" x2="16" y2="6"/>
              <line x1="8" y1="2" x2="8" y2="6"/>
              <line x1="3" y1="10" x2="21" y2="10"/>
            </svg>
            Book a call
          </a>
        </div>
      </div>
    </div>
  );
}
